In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
## Preprocess the data
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
## Encode categorical vairables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
## One hot Encoder 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
## Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
## Split the data into features and target
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
## Save the encoders and scaler for later use
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler, file)

## Train ANN Regression with the Problem Statement

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) ## Output Layer for regression
])

## Compile the Model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

## Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callbacks = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [14]:
## Set up Early Stopping
early_stopping_callbacks = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [15]:
## Train the model
history = model.fit(
    X_train, y_train,
    validation_data = (X_test,y_test),
    epochs = 100,
    callbacks = [early_stopping_callbacks, tensorboard_callbacks]
)

Epoch 1/100
250/250 [==============================] - 4s 8ms/step - loss: 100398.5859 - mae: 100398.5859 - val_loss: 98589.8047 - val_mae: 98589.8047
Epoch 2/100
250/250 [==============================] - 2s 8ms/step - loss: 99869.5547 - mae: 99869.5547 - val_loss: 97488.6562 - val_mae: 97488.6562
Epoch 3/100
250/250 [==============================] - 3s 13ms/step - loss: 97930.4453 - mae: 97930.4453 - val_loss: 94608.5156 - val_mae: 94608.5156
Epoch 4/100
250/250 [==============================] - 2s 7ms/step - loss: 93998.8594 - mae: 93998.8594 - val_loss: 89600.7109 - val_mae: 89600.7109
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 88009.2344 - mae: 88009.2344 - val_loss: 82797.1328 - val_mae: 82797.1328
Epoch 6/100
250/250 [==============================] - 2s 6ms/step - loss: 80474.5625 - mae: 80474.5625 - val_loss: 74984.7734 - val_mae: 74984.7734
Epoch 7/100
250/250 [==============================] - 3s 12ms/step - loss: 72372.3359 - mae: 72372.3359 - val_loss: 67324.0938 - val_mae: 67324.0938
Epoch 8/100
250/250 [==============================] - 2s 7ms/step - loss: 64782.9453 - mae: 64782.9453 - val_loss: 60821.4766 - val_mae: 60821.4766
Epoch 9/100
250/250 [==============================] - 2s 7ms/step - loss: 58753.2422 - mae: 58753.2422 - val_loss: 56051.6484 - val_mae: 56051.6484
Epoch 10/100
250/250 [==============================] - 3s 11ms/step - loss: 54655.6992 - mae: 54655.6992 - val_loss: 53129.6250 - val_mae: 53129.6250
Epoch 11/100
250/250 [==============================] - 4s 16ms/step - loss: 52260.6719 - mae: 52260.6719 - val_loss: 51748.3047 - val_mae: 51748.3047
Epoch 12/100
250/250 [==============================] - 5s 18ms/step - loss: 51081.0000 - mae: 51081.0000 - val_loss: 51188.5312 - val_mae: 51188.5312
Epoch 13/100
250/250 [==============================] - 3s 11ms/step - loss: 50580.7422 - mae: 50580.7422 - val_loss: 50992.0625 - val_mae: 50992.0625
Epoch 14/100
250/250 [==============================] - 5s 20ms/step - loss: 50357.6016 - mae: 50357.6016 - val_loss: 50887.5742 - val_mae: 50887.5742
Epoch 15/100
250/250 [==============================] - 5s 18ms/step - loss: 50244.1172 - mae: 50244.1172 - val_loss: 50833.4922 - val_mae: 50833.4922
Epoch 16/100
250/250 [==============================] - 2s 8ms/step - loss: 50170.8828 - mae: 50170.8828 - val_loss: 50785.9531 - val_mae: 50785.9531
Epoch 17/100
250/250 [==============================] - 2s 9ms/step - loss: 50112.3047 - mae: 50112.3047 - val_loss: 50741.3008 - val_mae: 50741.3008
Epoch 18/100
250/250 [==============================] - 2s 8ms/step - loss: 50064.8438 - mae: 50064.8438 - val_loss: 50691.8164 - val_mae: 50691.8164
Epoch 19/100
250/250 [==============================] - 2s 7ms/step - loss: 50014.7539 - mae: 50014.7539 - val_loss: 50661.9102 - val_mae: 50661.9102
Epoch 20/100
250/250 [==============================] - 2s 8ms/step - loss: 49974.7188 - mae: 49974.7188 - val_loss: 50632.9766 - val_mae: 50632.9766
Epoch 21/100
250/250 [==============================] - 2s 8ms/step - loss: 49940.4805 - mae: 49940.4805 - val_loss: 50592.7969 - val_mae: 50592.7969
Epoch 22/100
250/250 [==============================] - 2s 7ms/step - loss: 49906.5625 - mae: 49906.5625 - val_loss: 50569.9297 - val_mae: 50569.9297
Epoch 23/100
250/250 [==============================] - 2s 7ms/step - loss: 49876.8047 - mae: 49876.8047 - val_loss: 50553.8555 - val_mae: 50553.8555
Epoch 24/100
250/250 [==============================] - 4s 17ms/step - loss: 49850.1797 - mae: 49850.1797 - val_loss: 50529.5156 - val_mae: 50529.5156
Epoch 25/100
250/250 [==============================] - 2s 8ms/step - loss: 49825.8555 - mae: 49825.8555 - val_loss: 50503.5898 - val_mae: 50503.5898
Epoch 26/100
250/250 [==============================] - 2s 7ms/step - loss: 49802.8789 - mae: 49802.8789 - val_loss: 50478.3242 - val_mae: 50478.3242
Epoch 27/100
250/250 [==============================] - 2s 10ms/step - loss: 49782.2461 - mae: 49782.2461 - val_loss: 50460.4258 - val_mae: 50460.4258
Epoch 28/100
250/250 [==============================] - 2s 7ms/step - loss: 49763.6445 - mae: 49763.6445 - val_loss: 50444.9023 - val_mae: 50444.9023
Epoch 29/100
250/250 [==============================] - 2s 7ms/step - loss: 49746.3945 - mae: 49746.3945 - val_loss: 50443.7031 - val_mae: 50443.7031
Epoch 30/100
250/250 [==============================] - 2s 7ms/step - loss: 49728.7773 - mae: 49728.7773 - val_loss: 50423.1094 - val_mae: 50423.1094
Epoch 31/100
250/250 [==============================] - 2s 8ms/step - loss: 49712.5117 - mae: 49712.5117 - val_loss: 50411.7422 - val_mae: 50411.7422
Epoch 32/100
250/250 [==============================] - 2s 7ms/step - loss: 49699.6719 - mae: 49699.6719 - val_loss: 50393.5781 - val_mae: 50393.5781
Epoch 33/100
250/250 [==============================] - 2s 7ms/step - loss: 49684.1758 - mae: 49684.1758 - val_loss: 50391.1836 - val_mae: 50391.1836
Epoch 34/100
250/250 [==============================] - 2s 8ms/step - loss: 49671.8125 - mae: 49671.8125 - val_loss: 50381.6172 - val_mae: 50381.6172
Epoch 35/100
250/250 [==============================] - 2s 7ms/step - loss: 49656.8867 - mae: 49656.8867 - val_loss: 50384.2148 - val_mae: 50384.2148
Epoch 36/100
250/250 [==============================] - 2s 7ms/step - loss: 49647.8008 - mae: 49647.8008 - val_loss: 50369.8320 - val_mae: 50369.8320
Epoch 37/100
250/250 [==============================] - 2s 8ms/step - loss: 49637.5703 - mae: 49637.5703 - val_loss: 50358.6797 - val_mae: 50358.6797
Epoch 38/100
250/250 [==============================] - 2s 6ms/step - loss: 49623.8867 - mae: 49623.8867 - val_loss: 50366.4961 - val_mae: 50366.4961
Epoch 39/100
250/250 [==============================] - 2s 6ms/step - loss: 49616.8203 - mae: 49616.8203 - val_loss: 50373.6602 - val_mae: 50373.6602
Epoch 40/100
250/250 [==============================] - 2s 6ms/step - loss: 49605.6211 - mae: 49605.6211 - val_loss: 50357.9141 - val_mae: 50357.9141
Epoch 41/100
250/250 [==============================] - 2s 8ms/step - loss: 49595.1055 - mae: 49595.1055 - val_loss: 50350.0781 - val_mae: 50350.0781
Epoch 42/100
250/250 [==============================] - 2s 7ms/step - loss: 49587.2422 - mae: 49587.2422 - val_loss: 50345.9922 - val_mae: 50345.9922
Epoch 43/100
250/250 [==============================] - 2s 6ms/step - loss: 49580.4141 - mae: 49580.4141 - val_loss: 50346.0938 - val_mae: 50346.0938
Epoch 44/100
250/250 [==============================] - 2s 8ms/step - loss: 49570.7070 - mae: 49570.7070 - val_loss: 50339.5742 - val_mae: 50339.5742
Epoch 45/100
250/250 [==============================] - 3s 11ms/step - loss: 49561.9062 - mae: 49561.9062 - val_loss: 50327.3633 - val_mae: 50327.3633
Epoch 46/100
250/250 [==============================] - 2s 9ms/step - loss: 49555.7695 - mae: 49555.7695 - val_loss: 50331.2891 - val_mae: 50331.2891
Epoch 47/100
250/250 [==============================] - 2s 8ms/step - loss: 49547.3320 - mae: 49547.3320 - val_loss: 50328.2148 - val_mae: 50328.2148
Epoch 48/100
250/250 [==============================] - 2s 6ms/step - loss: 49539.3398 - mae: 49539.3398 - val_loss: 50336.0000 - val_mae: 50336.0000
Epoch 49/100
250/250 [==============================] - 2s 7ms/step - loss: 49535.6641 - mae: 49535.6641 - val_loss: 50338.0781 - val_mae: 50338.0781
Epoch 50/100
250/250 [==============================] - 2s 8ms/step - loss: 49529.3594 - mae: 49529.3594 - val_loss: 50344.0859 - val_mae: 50344.0859
Epoch 51/100
250/250 [==============================] - 2s 6ms/step - loss: 49523.1406 - mae: 49523.1406 - val_loss: 50333.8867 - val_mae: 50333.8867
Epoch 52/100
250/250 [==============================] - 2s 6ms/step - loss: 49515.3828 - mae: 49515.3828 - val_loss: 50326.8008 - val_mae: 50326.8008
Epoch 53/100
250/250 [==============================] - 2s 6ms/step - loss: 49506.1055 - mae: 49506.1055 - val_loss: 50330.4609 - val_mae: 50330.4609
Epoch 54/100
250/250 [==============================] - 2s 7ms/step - loss: 49501.1875 - mae: 49501.1875 - val_loss: 50327.7812 - val_mae: 50327.7812
Epoch 55/100
250/250 [==============================] - 2s 7ms/step - loss: 49499.6406 - mae: 49499.6406 - val_loss: 50320.1133 - val_mae: 50320.1133
Epoch 56/100
250/250 [==============================] - 2s 6ms/step - loss: 49489.8828 - mae: 49489.8828 - val_loss: 50328.2539 - val_mae: 50328.2539
Epoch 57/100
250/250 [==============================] - 2s 7ms/step - loss: 49485.6719 - mae: 49485.6719 - val_loss: 50328.7305 - val_mae: 50328.7305
Epoch 58/100
250/250 [==============================] - 2s 6ms/step - loss: 49478.6289 - mae: 49478.6289 - val_loss: 50323.9414 - val_mae: 50323.9414
Epoch 59/100
250/250 [==============================] - 2s 8ms/step - loss: 49473.3125 - mae: 49473.3125 - val_loss: 50317.8281 - val_mae: 50317.8281
Epoch 60/100
250/250 [==============================] - 3s 12ms/step - loss: 49468.9375 - mae: 49468.9375 - val_loss: 50318.5703 - val_mae: 50318.5703
Epoch 61/100
250/250 [==============================] - 1s 5ms/step - loss: 49462.2812 - mae: 49462.2812 - val_loss: 50320.7422 - val_mae: 50320.7422
Epoch 62/100
250/250 [==============================] - 1s 5ms/step - loss: 49457.4727 - mae: 49457.4727 - val_loss: 50320.0117 - val_mae: 50320.0117
Epoch 63/100
250/250 [==============================] - 1s 6ms/step - loss: 49453.3008 - mae: 49453.3008 - val_loss: 50323.5273 - val_mae: 50323.5273
Epoch 64/100
250/250 [==============================] - 2s 8ms/step - loss: 49448.9375 - mae: 49448.9375 - val_loss: 50318.8320 - val_mae: 50318.8320
Epoch 65/100
250/250 [==============================] - 1s 6ms/step - loss: 49443.7617 - mae: 49443.7617 - val_loss: 50310.4414 - val_mae: 50310.4414
Epoch 66/100
250/250 [==============================] - 2s 7ms/step - loss: 49436.6016 - mae: 49436.6016 - val_loss: 50310.5352 - val_mae: 50310.5352
Epoch 67/100
250/250 [==============================] - 2s 7ms/step - loss: 49434.1875 - mae: 49434.1875 - val_loss: 50316.2188 - val_mae: 50316.2188
Epoch 68/100
250/250 [==============================] - 2s 7ms/step - loss: 49428.3477 - mae: 49428.3477 - val_loss: 50313.4102 - val_mae: 50313.4102
Epoch 69/100
250/250 [==============================] - 2s 7ms/step - loss: 49428.2148 - mae: 49428.2148 - val_loss: 50306.6641 - val_mae: 50306.6641
Epoch 70/100
250/250 [==============================] - 1s 6ms/step - loss: 49421.8711 - mae: 49421.8711 - val_loss: 50307.5156 - val_mae: 50307.5156
Epoch 71/100
250/250 [==============================] - 2s 6ms/step - loss: 49417.1445 - mae: 49417.1445 - val_loss: 50313.6016 - val_mae: 50313.6016
Epoch 72/100
250/250 [==============================] - 2s 6ms/step - loss: 49412.7031 - mae: 49412.7031 - val_loss: 50300.8359 - val_mae: 50300.8359
Epoch 73/100
250/250 [==============================] - 2s 8ms/step - loss: 49409.5156 - mae: 49409.5156 - val_loss: 50311.6992 - val_mae: 50311.6992
Epoch 74/100
250/250 [==============================] - 2s 7ms/step - loss: 49405.8828 - mae: 49405.8828 - val_loss: 50307.9609 - val_mae: 50307.9609
Epoch 75/100
250/250 [==============================] - 1s 6ms/step - loss: 49406.2656 - mae: 49406.2656 - val_loss: 50316.6289 - val_mae: 50316.6289
Epoch 76/100
250/250 [==============================] - 2s 6ms/step - loss: 49398.3359 - mae: 49398.3359 - val_loss: 50306.9883 - val_mae: 50306.9883
Epoch 77/100
250/250 [==============================] - 1s 6ms/step - loss: 49396.8945 - mae: 49396.8945 - val_loss: 50303.5352 - val_mae: 50303.5352
Epoch 78/100
250/250 [==============================] - 2s 8ms/step - loss: 49388.7344 - mae: 49388.7344 - val_loss: 50308.1211 - val_mae: 50308.1211
Epoch 79/100
250/250 [==============================] - 1s 6ms/step - loss: 49389.6328 - mae: 49389.6328 - val_loss: 50299.3242 - val_mae: 50299.3242
Epoch 80/100
250/250 [==============================] - 1s 6ms/step - loss: 49387.2617 - mae: 49387.2617 - val_loss: 50301.4062 - val_mae: 50301.4062
Epoch 81/100
250/250 [==============================] - 2s 7ms/step - loss: 49382.0742 - mae: 49382.0742 - val_loss: 50306.1758 - val_mae: 50306.1758
Epoch 82/100
250/250 [==============================] - 1s 5ms/step - loss: 49379.6133 - mae: 49379.6133 - val_loss: 50301.0273 - val_mae: 50301.0273
Epoch 83/100
250/250 [==============================] - 1s 5ms/step - loss: 49376.2539 - mae: 49376.2539 - val_loss: 50297.5234 - val_mae: 50297.5234
Epoch 84/100
250/250 [==============================] - 1s 5ms/step - loss: 49371.8203 - mae: 49371.8203 - val_loss: 50301.8477 - val_mae: 50301.8477
Epoch 85/100
250/250 [==============================] - 2s 6ms/step - loss: 49369.9062 - mae: 49369.9062 - val_loss: 50310.1055 - val_mae: 50310.1055
Epoch 86/100
250/250 [==============================] - 2s 7ms/step - loss: 49365.4219 - mae: 49365.4219 - val_loss: 50305.8398 - val_mae: 50305.8398
Epoch 87/100
250/250 [==============================] - 1s 5ms/step - loss: 49362.3359 - mae: 49362.3359 - val_loss: 50311.8398 - val_mae: 50311.8398
Epoch 88/100
250/250 [==============================] - 1s 5ms/step - loss: 49361.3516 - mae: 49361.3516 - val_loss: 50314.1523 - val_mae: 50314.1523
Epoch 89/100
250/250 [==============================] - 2s 7ms/step - loss: 49356.8906 - mae: 49356.8906 - val_loss: 50315.4648 - val_mae: 50315.4648
Epoch 90/100
250/250 [==============================] - 1s 5ms/step - loss: 49356.0156 - mae: 49356.0156 - val_loss: 50315.6289 - val_mae: 50315.6289
Epoch 91/100
250/250 [==============================] - 3s 11ms/step - loss: 49352.8984 - mae: 49352.8984 - val_loss: 50317.2383 - val_mae: 50317.2383
Epoch 92/100
250/250 [==============================] - 2s 7ms/step - loss: 49346.8750 - mae: 49346.8750 - val_loss: 50316.7383 - val_mae: 50316.7383
Epoch 93/100
250/250 [==============================] - 1s 5ms/step - loss: 49343.9297 - mae: 49343.9297 - val_loss: 50322.7305 - val_mae: 50322.7305

In [16]:
%reload_ext tensorboard

In [18]:
%tensorboard --logdir refressionlogs/fit

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [19]:
## Evaluate the model on the test data
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 1s 6ms/step - loss: 50297.5234 - mae: 50297.5234
Test MAE : 50297.5234375

In [20]:
model.save('regression_model.h5')

c:\Users\User\anaconda3\envs\ann_ml\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(